export const routes: any = {
  ROOT: '/',
  ANY: '*',
  AUTH: 'auth',
  SIGN_IN: 'sign-in',
  BIRTH_DATE: 'birth-date',
  FORGOT_PASSWORD: 'forgot-password',
  SIGN_UP: 'sign-up',
  SELECT_ROLE: 'select-role',
  GET_STARTED: 'get-started',
  STUDENT: 'student',
  PARENT: 'parent',
  TEACHER: 'teacher',
  FIRST_LOGIN_STUDENT: 'get-started/student',
  FIRST_LOGIN_PARENT: 'get-started/parent',
  FIRST_LOGIN_TEACHER: 'get-started/teacher',
  DASHBOARD: 'dashboard',
  STUDENT_DASHBOARD: 'student/dashboard',
  PARENT_DASHBOARD: 'parent/dashboard',
  TEACHER_DASHBOARD: 'teacher/dashboard',
  STUDENT_DOB: 'date-of-birth',
  ADMIN: 'admin',
}
