export const routes: any = {
  ROOT: "/",
  ANY: "*",
  AUTH: "/auth",
  SIGN_IN: "login",
  BIRTH_DATE: "birth-date",
  FORGOT_PASSWORD: "forgot-password",
  SIGN_UP: "sign-up",
  SELECT_ROLE: "sign-up/:role",
  FIRST_LOGIN_PARENT: "sign-up/:role/parent-details",
  FIRST_LOGIN_TEACHER: "sign-up/:role/teacher-details",
  GET_STARTED: "get-started",
  DASHBOARD: "dashboard",
  STUDENT_DOB: "date-of-birth",
};
