name: CI::Prod

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  shared-workflow:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/ci.yaml
    name: Prod CI
    with:
      env: prod
      backendURL: https://wizer-be-prod-g372w7tgka-uc.a.run.app
      WSURL: wss://wizer-be-prod-g372w7tgka-uc.a.run.app
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
