name: CI::Staging

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  shared-workflow:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/ci.yaml
    name: Staging CI
    with:
      env: staging
      backendURL: https://wizer-be-staging-g372w7tgka-uc.a.run.app
      WSURL: wss://wizer-be-staging-g372w7tgka-uc.a.run.app
    secrets:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
